### ISSUE TITLE
custom pfp

### ISSUE THREAD

**Issue by LankyBox01** [jeffalo/wasteof.money#118]
pls let us do custom pfp

**Comment by jeffalo** [comment]
custom profile pictures are supported in wasteof.money legacy.

**Comment by return-misaPuding** [comment]
Can you make a separate repo for storing the unnuxted legacy version plz?
Also how's the nuxtification itself going?

Dne út 22. 6. 2021 6:15 uživatel jeffalo ***@***.***> napsal:

**Comment by jeffalo** [comment]
this repo will be archived once the new version launches. i am still working on whether the new one should be open source or not. i kinda like the peace of working on my own.

nuxtification is going great. see https://wasteof.money

**Comment by return-misaPuding** [comment]
PLZ make it open-source :3, closed-source is sussy and has slow bugfixes :/
:/ :/

Dne st 30. 6. 2021 14:32 uživatel jeffalo ***@***.***> napsal:

**Comment by jeffalo** [comment]
open source can be slower for large projects like this. code has to be reviewed, commit messages have to be descriptive, etc. closed source can be much faster.
