### ISSUE TITLE
development without db?

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#15]
installing mongodb locally to develop is not easy for contributors, perhaps there could be a mode which simulates having a db? perhaps it just lists the ejs pages and renders them with template values?

any suggestions?

**Comment by jeffalo** [comment]
@GrahamSH-LLK setup with mongo atlas free tier, perhaps those instructions could be there

**Comment by GrahamSH-LLK** [comment]
- First, make an account at https://www.mongodb.com/cloud/atlas/register. Fill out the fields, or sign in with Google.
- When it prompts you to pick a provider, pick any option
- Pick the free plan
- Keep the default settings for server options, and submit
- On the home screen, wait for the blue status bar to dissapear.
- While you are waiting, follow the readme instructions until .env
More coming

**Comment by pufferfish101007** [comment]
An easier way would be to use [jsoning](https://npmjs.org/package/jsoning) - no setup is required. Sorry, I'm obsessed with jsoning 😆

**Comment by jeffalo** [comment]
but then we'd have to rewrite our database based code... i think graham's solution works well
