### ISSUE TITLE
full navigation should work with keyboard

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#24]

**Comment by wgyt** [comment]
@jeffalo Would this be like Discord's keyboard shortcuts(Ctrl + /) but with shortcuts customized for wasteof.money?

**Comment by GrahamSH-LLK** [comment]
No, I think just tab and enter. Pretty much everything works already.

**Comment by wgyt** [comment]
> No, I think just tab and enter. Pretty much everything works already.

That makes sense, this would also be a win for accessibility.
