### ISSUE TITLE
site-wide rules

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#29]
we want to encourage freedom of expression, but keep a respectful and safe environment, todo make site rules that are required to sign up

**Comment by GrahamSH-LLK** [comment]
Wasteof.money encourages freedom of expression, with a few rules.

1. Stay respectful
Always stay respectful on wasteof.money, no matter who you are talking about or to. If you aren't respectful, you may be banned.
2. Keep personal info private
Keep in mind that _anyone_ can see what you write, and can do bad things with that. This includes full names, email addresses, and addresses.
3. Be honest
Being honest is really important. Never impersonate people, or try to trick anyone. Lying or impersonating is grounds for being banned.

**Comment by jeffalo** [comment]
thanks!
