### ISSUE TITLE
handle token edge case

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#30]
currently, there's a rare (but possible) chance of 2 users getting the same login token.

**Comment by pufferfish101007** [comment]
@jeffalo I think this can be closed because it's accounted for at https://github.com/jeffalo/wasteof.money/blob/9696852e1eec1c4a3268962c78f60420b9b3560f/index.js#L905

**Comment by jeffalo** [comment]
yep! i fixed it without closing the issue
