### ISSUE TITLE
assume userpage?

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#47]
if you go to wasteof.money/jeffalo and the following conditions are met you should go to my profile
- there is no page called jeffalo
- jeffalo is a user on the site who is not banned or deleted

what do you guys think? sites like twitter do it, but it could lead to bad things if its not handled properly

**Comment by pufferfish101007** [comment]
I think that could work... maybe we could do what npm does with packages and just redirect to https://wasteof.money/users/jeffalo

**Comment by jeffalo** [comment]
ah yes thats what i meant. so wasteof.money/jeffalo would redirect to wasteof.money/users/jeffalo
