### ISSUE TITLE
rethink posts

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#48]
currently /post/:id redirects you to the poster's profile with a long ugly query string to load one specific post

perhaps posts should have their own page with a button to load more posts by that user.

then on a userpage, clicking post id/reply count/whatever should take you to the dedicated post page where you can reply and see other's replies.

what do you guys think?

**Comment by GrahamSH-LLK** [comment]
Interesting.. That sounds good!

**Comment by jeffalo** [comment]
we might need to use vue components to make development easier. no clue how to do that though

**Comment by pufferfish101007** [comment]
> we might need to use vue components to make development easier. no clue how to do that though

Yes please do that it will make testing easier as well I can do that but ssr or not? Discuss on the discord sorry I get really excited when vue is mentioned 🥳
