### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#5]
make readme.md file

**Comment by jeffalo** [comment]
![image](https://user-images.githubusercontent.com/40470736/101082495-d427f400-35ab-11eb-9972-3e60e025050f.png)
![image](https://user-images.githubusercontent.com/40470736/101082518-ddb15c00-35ab-11eb-933b-babb15b19cd3.png)
![image](https://user-images.githubusercontent.com/40470736/101082530-e2761000-35ab-11eb-9728-373d29ab7579.png)

**Comment by jeffalo** [comment]
environment variables (.env file)
mongo, needs DB_URL env variable
optional LISTEN_PORT env variable default 8080

**Comment by jeffalo** [comment]
setup:
install node, npm and mongodb

`git clone https://github.com/jeffalo/wasteof.money.git`
`cd wasteof.money`
`npm i`

make .env file
include `DB_URL=localhost/social` or whatever else

`node .`

**Comment by GrahamSH-LLK** [comment]
## js with comments 😲
```js
console.log('hello!!!!') // this code does epic things
alert('xss???')
```
## diff test
```diff
public class Hello1
{
   public static void Main()
   {
-      System.Console.WriteLine("Hello, World!");
+      System.Console.WriteLine("good bye!");
   }
}
```
## html with javascript 🤯
```html
<button>i am button</button>
<script>
   console.log('epic')
</script>
```
