### ISSUE TITLE
chat2 integration 

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#6]
some kind of integration with chat2?

**Comment by jeffalo** [comment]
(chat2 being my chat software [chat.jeffalo.net](https://chat.jeffalo.net))

**Comment by GrahamSH-LLK** [comment]
> (chat2 being my chat software [chat.jeffalo.net](https://chat.jeffalo.net))

That makes sense. It would be cool. You would have to connect both auth systems somehow.

**Comment by jeffalo** [comment]
rethinking: this wouldn't be great. writing a seperate simple chat system would probably be a lot better.
