### ISSUE TITLE
cookie parsing error

### ISSUE THREAD

**Issue by VelocityDesign** [jeffalo/wasteof.money#63]
Gives me this error:
C:\Users\#########\wasteof.money\node_modules\cookie\index.js:51
    throw new TypeError('argument str must be a string');
          ^

TypeError: argument str must be a string
    at Object.parse (C:\Users\#########\wasteof.money\node_modules\cookie\index.js:51:11)
    at Namespace.<anonymous> (C:\Users\#########\wasteof.money\index.js:800:26)
    at Namespace.emit (node:events:376:20)
    at C:\Users\#######\wasteof.money\node_modules\socket.io\dist\namespace.js:129:27
    at processTicksAndRejections (node:internal/process/task_queues:75:11)

I am using AWS clusters with atlas.

**Comment by jeffalo** [comment]
does this happen at startup or when you do a specific thing?

**Comment by jeffalo** [comment]
https://github.com/jeffalo/wasteof.money/blob/53d4e3f2bdd675b1a73d0aff76af8a5eaee68da6/index.js#L800

**Comment by VelocityDesign** [comment]
This happens when I try to create an account

**Comment by VelocityDesign** [comment]
Sorry for the brief issue I was tired.

**Comment by jeffalo** [comment]
> This happens when I try to create an account

I'll take a look
