### ISSUE TITLE
grid text going on top

### ISSUE THREAD

**Issue by jeffalo** [jeffalo/wasteof.money#80]
apart from the duplicate followers, 
![IMG_20210115_075014](https://user-images.githubusercontent.com/40470736/104691368-61f81280-5706-11eb-910d-6094e935d33f.jpg)

Donald's name overlaps biden

**Comment by GrahamSH-LLK** [comment]
This is a tricky design scenario. Do we add ellipses at the end?

**Comment by jeffalo** [comment]
perhaps a smaller grid? 2 columns and ellipses might be it

**Comment by jeffalo** [comment]
![image](https://user-images.githubusercontent.com/40470736/104746869-22561880-5750-11eb-8f50-386c5b51d630.png)
